# serverless.yml


service: serverless-flask-persistence


plugins:

  - serverless-python-requirements

  - serverless-wsgi


custom:

  wsgi:

    app: app.app

    packRequirements: false

  pythonRequirements:

    dockerizePip: non-linux


provider:

  name: aws

  runtime: python3.7

  stage: dev

  region: us-west-2

  lambdaHashingVersion: 20201221

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:

  app:

    handler: wsgi_handler.handler

    events:

      - http: ANY /

      - http: 'ANY {proxy+}'
      